#!/usr/bin/env sh

day=$(date +%a)
month=$(date +%B)
day_full=$(date +%A)
day_of_month=$(date +%d)

bold=$(tput bold)
reset=$(tput sgr0)

no_events=false

clear_data() {
    current_date=$(date +%m/%d/%Y)
    file="data"
    temp_file="temp_data"
    touch "$temp_file"

    if [ -e "$file" ]; then
        while IFS=';' read -r date_in_file event urgency; do
            formatted_date=$(date -d "$date_in_file" +%m/%d/%Y)
            if [ "$formatted_date" \> "$current_date" ]; then
                echo "$date_in_file;$event;$urgency" >> "$temp_file"
            else
                if [ "$formatted_date" == "$current_date" ]; then
                echo "$date_in_file;$event;$urgency" >> "$temp_file"
                else
                    no_events=true
                fi
            fi

    done < "$file"
    mv "$temp_file" "$file"
    else
        echo "ERROR: data file not found!"
    fi
}

get_info() {
  current_date=$(date +%m/%d/%Y)
  line_count=0
  today_count=0
  urgent_count=0
  very_urgent=0
      while IFS=';' read -r date_in_file event urgency; do
          ((line_count++))
          if [ "$date_in_file" == "$current_date" ]; then
              ((today_count++))
          fi
          if [ "$urgency" == "u" ]; then
              ((urgent_count++))
          fi
          if [ "$urgency" == "U" ]; then
              ((very_urgent++))
          fi
      done < "data"

  echo "
                 ___,___,_______,____
                |  :::|///./||'||    L
                |  :::|//.//|| || H)  |
                |  :::|/.///|!!!|     | events: $line_count
                |   _______________   | today: $today_count
                |  |:::::::::::::::|  | urgent: $urgent_count
                |  |_______________|  | very urgent: $very_urgent
                |  |_______________|  | 
                |  |_______________|  | 
                |  |_______________|  |
                ||_|     TODO      ||_|
                |__|_______________|__|" 
}

clear_all_data() {
    echo "are you sure you want to delete all scheduled events (y/n)?"
    while true; do
        read -s -n 1 key
        case $key in
            y|Y)
                echo "clearing all scheduled events" | lolcat
                truncate -s 0 "data"
                echo " 
                 ___,___,_______,____
                |  :::|///./||'||    L
                |  :::|//.//|| || H)  |
                |  :::|/.///|!!!|     | much empty
                |   _______________   |   * cricket noises * 
                |  |:::::::::::::::|  | 
                |  |_______________|  |   big nothing
                |  |_______________|  | no todos
                |  |_______________|  | 
                |  |_______________|  |
                ||_|     TODO      ||_|
                |__|_______________|__|"
                exit 0
                ;;
            n|N)
                echo "cancelled"
                exit 0
                ;;
            *)
                echo "please type y/n"
        esac
    done
}

process_data() {
  #format: dd/mm/yyyy;<event>;[U|u|n]
  current_date=$(date +%m/%d/%Y)
  file="data"
  if [ -e "$file" ]; then
    while IFS= read -r line; do
        IFS=';' read -r date_in_file event urgency ignored <<< "$line"
            if [ "$date_in_file" == "$current_date" ]; then
                if [ "$urgency" == "U" ]; then
                    echo "$bold   (URGENT) $event $reset" | lolcat
                else
                    if [ "$urgency" == "u" ]; then
                        echo "   (URGENT) $event"
                    else
                        echo "   $event"
                    fi
                fi
            fi
    done < "$file"
  else
    echo "File not found: $file"
  fi
}

if [ "$1" = "--info" ]; then
    get_info
fi

if [ "$1" = "--help" ]; then
    echo "$bold Don't panic!$reset" | lolcat
    echo " --help: prints this helpful message"
    echo " --add mm/dd/yyy event [string] urgency [U|u|n]: adds event to reminders"
    echo " --add --today event urgency: adds event with today's date"
    echo "    urgency options: n neutral, u urgent, U very urgent"
    echo " --clear: clears all scheduled events"
    echo " --info: prints informatino on scheduled events"
fi

if [ "$1" = "--clear" ]; then
    clear_all_data
fi


if [ "$1" = "--add" ]; then
    date_user=$2
    event_user=$3
    urgency=$4
    if date -d "$date_user" "+%m/%d/%Y" >/dev/null 2>&1; then
        if [ "$date_user" = "--today" ]; then
           date_user=$(date +%m/%d/%Y)
        else
           echo "ERROR: wrong date format: expected mm/dd/yyyy"
           echo "use --help option for usage"
           exit 0
        fi
    fi

    if [[ "$urgency" = "u" || "$urgency" = "n" ]]; then
       urgency_write="$urgency"
       else
           if [[ "$urgency" = "U" ]]; then
               urgency_write="$urgency"
           else
               echo "ERROR: unexpected urgency string:"$urgency", expected U, u or n"
               echo "use --help option for usage"
               exit 0
           fi
    fi

    echo "$date_user;$event_user;$urgency" >> data
    echo "added new event!" | lolcat
    echo "
            ___,___,_______,____
            |  :::|///./||'||    L
            |  :::|//.//|| || H)  |TODO added!
            |  :::|/.///|!!!|     | TODO TODO TODO + ++
            |   _______________   |  TODO TODO TODO TODO+
            |  |:::::::::::::::|  | TODO TODO TODO TODO TODO + +
            |  |_______________|  | TODO TODO TODO ++
            |  |_______________|  |TODO TODO +  +
            |  |_______________|  | TODO ++
            |  |_______________|  |
            ||_|     TODO      ||_|
            |__|_______________|__|"
fi

if [ -z "$1" ]; then
    echo "$bold Greetings Master, today is $day_full, $month $day_of_month. $reset" | lolcat
    echo "On the agenda today: "

    case $day in
        "Mon")
        day="Mon"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        ;;
        "Wed")
        day="Wed"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        "Tue")
        day="Tue"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        "Thu")
        day="Thu"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        "Fri")
        day="Fri"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        "Sat")
        day="Sat"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        "Sun")
        day="Sun"
        filename="data_weekly"
        python weekly.py "$day" "$filename"
        process_data
        clear_data
        ;;
        *)
        echo "ERROR: sth is seriously wrong, this should not happen."
        ;;
        #if [ "$no_events"="true" ]; then
         #   echo "    no events, enjoy your day!"
        #fi
 esac
fi
